_meta_database:
  help: Download and build sequence databases and indices.
path:
  help: Change location of default database.
download_only:
  default: False
  action: 'store_true'
  help: Only perform download step.
build_only:
  default: False
  action: 'store_true'
  help: Build from local database that exists at this path.
includedb:
  default: ["genbank","Complete Genome","Chromosome","Scaffold"]
  nargs: +
  help: Subsets of defaults can be specified for download or partitioning
ff_list:
  help: Used with build_only to create a local database from a filelist of GenBank Flat files
taxonomy_path:
  help: Used with build_only and should be a local mirror of ftp://ftp.ncbi.nih.gov/pub/taxonomy/ directory


