language: python
python:
  - 3.6

# Setup anaconda
before_install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.

  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r

  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --set anaconda_upload no

# Install packages
install:
  - conda install -q python=3.6 pip requests conda-build jinja2 anaconda-client 
  - conda build . -c bioconda -c etetoolkit -c conda-forge
  - conda install mtsv --use-local -c tara_furstenau -c bioconda -c etetoolkit -c conda-forge
script:
  - mtsv --help
