{% set data = load_setup_py_data() %}

package:
  name: 'mtsv'
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  path: .

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  # string: {{ environ.get('GIT_BUILD_STR', '') }}
  entry_points:
    - mtsv = mtsv.__main__:cli
    - mtsv_setup = mtsv.mtsv_prep.main:main
  skip: true  # [osx or not py36]

requirements:
  build:
    - {{ compiler('cxx')}}
  host:
    - python
    - setuptools
    - zlib
    - click
  run:
    - python
    - snakemake>=5.4
    - pandas>=0.20.3
    - ete3
    - matplotlib
    - seaborn
    - biopython
    - argutils
    - jinja2
    - statsmodels
    - six
    - mtsv-tools
    - numpy
    - pyyaml
    - fastp
    - click
    - zlib
    - wgfast==1.0.3
    - concoct
    - megahit
    - bwa
    - samtools
    - gsl
    - pytables

test:
  imports:
    - mtsv
  # requires:
  #   - pytest
  commands:
    - mtsv --help > /dev/null
    - mtsv_setup --help > /dev/null
    # - py.test --pyargs mtsv
    
about:
  home: https://github.com/FofanovLab/MTSv
  summary: MTSv is a suite of metagenomic binning and analysis tools.
  license: MIT
  license_file: LICENSE


