{% set name = "mtsv" %}
{% set version = "2.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: .

build:
  number: 0
  entry_points:
    - mtsv = mtsv.__main__:cli
    - mtsv_setup = mtsv.mtsv_prep.main:main
  skip: true  # [osx or not py36]

requirements:
  build:
    - {{ compiler('cxx')}}
  host:
    - python>=3.6
    - pip
    - zlib
    - click
  run:
    - python
    - snakemake>=5.4
    - pandas>=0.20.3
    - ete3
    - matplotlib
    - seaborn
    - biopython
    - argutils
    - jinja2
    - statsmodels
    - six
    - mtsv-tools>=1.0.1
    - numpy
    - pyyaml
    - fastp
    - click
    - zlib
    - gsl
    - pytables

test:
  imports:
    - mtsv

  commands:
    - mtsv --help > /dev/null
    - mtsv_setup --help > /dev/null

    
about:
  home: https://github.com/FofanovLab/MTSv
  summary: MTSv is a suite of metagenomic binning and analysis tools.
  license: MIT
  license_file: LICENSE


