{% set data = load_setup_py_data() %}

package:
  name: 'mtsv'
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/FofanovLab/MTSv

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  # string: {{ environ.get('GIT_BUILD_STR', '') }}
  binary_relocation: True
  entry_points:
    - mtsv = mtsv.main:main
    - mtsv_setup = mtsv.mtsv_prep.main:main
    - mtsv_plugin = mtsv.mtsv_plugin.main:main

requirements:
  build:
    - rust>=1.24.0
    - python==3.6
    - setuptools
  run:
    - python==3.6
    - snakemake>=4.1
    - pandas>=0.20.3
    - ete3
    - ete_toolchain
    - biopython
    - scipy
    - six
    - numpy
    - pyyaml
    - click
    - zlib
    - wgfast

test:
  imports:
    - mtsv
  requires:
    - pytest
  commands:
    - py.test --pyargs mtsv


