{% set data = load_setup_py_data() %}

package:
  name: 'mtsv'
  version: {{ data.get('version') }}

source:
  path: ./  #update with git repo

build:
  number: 0
  entry_points:
    - mtsv = mtsv.main:main
    - mtsv_setup = mtsv.mtsv_prep.main:main
    - mtsv_plugin = mtsv.mtsv_plugin.main:main

requirements:
  build:
    - rust>=1.24.0
    - python>=3.5
    - setuptools
  run:
    - python>=3.5
    - snakemake>=4.1
    - pandas>=0.20.3
    - ete3
    - ete_toolchain
    - biopython
    - six
    - numpy
    - pyyaml
    - click




